enable_ufw_firewall: true

install_packages:
  - postfix
  - unzip
  - libcap2-bin
  - python-is-python3
  - python3-pip

hostname: xphish
xphish_user: ubuntu
postfix_hostname: xphish
postfix_inet_interfaces: 127.0.0.1
xphish_domain: xphish.local
xphish_ssl_cert_path: /etc/ssl/private/xphish.pem
xphish_csr_path: /etc/ssl/csr/xphish.csr
xphish_crt_path: /etc/ssl/crt/xphish.crt
# Required if changing /etc/hostname to something different.
reboot_box: true
